### ISSUE TITLE
"0" should be highlighted when you click "Fund"

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/ui#195]
When you click "Fund", the text in the input box should automatically be selected. Otherwise you have to manually delete "0" before entering the amount you wish to fund.

**Comment by derekrazo** [comment]
Yessssssss

**Comment by derekrazo** [comment]
#quickfix @ahdinosaur ?

**Comment by ahdinosaur** [comment]
yup. question: should it select the input text when it already has an amount and you click on it?

**Comment by jonlemmon** [comment]
yeah i reckon

**Comment by jonlemmon** [comment]
as long as up and down still work to increase/decrease the amount while
it's highlighted.

**Comment by ahdinosaur** [comment]
done with #196
